[phases.setup]
nixPkgs = ["php84", "nodejs", "bun", "php84Packages.composer"]

[phases.install]
cmds = [
    "composer install --no-interaction --optimize-autoloader --no-dev",
    "npm install --legacy-peer-deps",
    "cd whatsapp-server && bun install"
]

[phases.build]
cmds = [
    "npm run build"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
